project:
  type: website

website:
  title: "ISSS608-AY2023-24T3"
  navbar:
    left:
      - text: Hands-on Exercise
        menu: 
          - text: "Hands-on Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Hands-on Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Hands-on Exercise 3a"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03a.html"
          - text: "Hands-on Exercise 3b"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03b.html"
          - text: "Hands-on Exercise 4a"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04a.html"
          - text: "Hands-on Exercise 4b"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04b.html" 
          - text: "Hands-on Exercise 4c"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04c.html"
          - text: "Hands-on Exercise 05"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Hands-on Exercise 06"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Hands-on Exercise 07"
            href: "Hands-on_Ex/Hands-on_Ex07/Hands-on_Ex07.html"
          - text: "Hands-on Exercise 08a"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_1.html"
          - text: "Hands-on Exercise 08b"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_2.html"
          - text: "Hands-on Exercise 08c"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08_3_1.html"
          #- text: "Hands-on_Ex/Hands-on_Ex08a"
            #href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08a.html"
          #- text: "Hands-on_Ex/Hands-on_Ex09"
            #href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          #- text: "Hands-on_Ex/Hands-on_Ex10"
            #href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
          
      - text: In-class Exercise
        menu: 
          - text: "In-class Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "In-class Exercise 2"
            href: "In-class_Ex/In-class_Ex02/In-class_Ex02.html"
          - text: "In-class Exercise 4"
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
          - text: "In-class Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
          - text: "In-class Exercise 6"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06.html"
          - text: "In-class Exercise 6 Network"
            href: "In-class_Ex/In-class_Ex06/In-class_Ex06A.html"
            
      - text: Take-home Exercise
        menu: 
          - text: "Take-home Exercise 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Take-home Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Take-home Exercise 3 - EDA"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03_EDA_0906.html"
          - text: "Take-home Exercise 3 - Qn"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03_Q_0906.html"
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: 
        - cosmo
        - minty.scss
    css: styles.css
    toc: true

editor: visual
